//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseItem()
        {
            this.AuditExpenseItems = new HashSet<AuditExpenseItem>();
        }
    
        public long ID { get; set; }
        public int ExpenseType { get; set; }
        public string BillNumber { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public long FormID { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditExpenseItem> AuditExpenseItems { get; set; }
        public virtual ExpenseForm ExpenseForm { get; set; }
        public virtual ExpenseType ExpenseType1 { get; set; }
    }
}
