//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExpenseType { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ExpenseType ExpenseType1 { get; set; }
    }
}
