//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditExpenseItem
    {
        public long ID { get; set; }
        public Nullable<long> ExpenseItemID { get; set; }
        public Nullable<int> ExpenseType { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<long> FormID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ExpenseItem ExpenseItem { get; set; }
    }
}
