//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseForm()
        {
            this.AuditExpenseForms = new HashSet<AuditExpenseForm>();
            this.ExpenseItems = new HashSet<ExpenseItem>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public string RejectReason { get; set; }
        public int Status { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditExpenseForm> AuditExpenseForms { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseItem> ExpenseItems { get; set; }
    }
}
